list_tags:
    defaults: { _controller: "ValouleloupIssueBundle:Tag:list" }
    methods: [GET]
    options:
        expose: true
    path: ""

add_tag:
    defaults: { _controller: "ValouleloupIssueBundle:Tag:new" }
    methods: [GET]
    options:
        expose: true
    path: "/new"

create_tag:
    defaults: { _controller: "ValouleloupIssueBundle:Tag:create" }
    methods: [POST]
    options:
        expose: true
    path: "/create"